### ISSUE TITLE
No progress output from `pv`, backtrace at end of run

### ISSUE THREAD

**Issue by chrivers** [whoschek/bzfs#4]
**Describe the bug**
I've just tried bzfs for the first time, and I like it! I only had a small problem so far.

I'm trying to run local replication to a backup dataset, like so:

```
./bzfs --recursive archive/vms vault-disk3/vms
```

Even though `pv` is installed, I get no progress output. But at the end of the run, I get this:

```
Traceback (most recent call last):
  File "/root/git/bzfs/bzfs/./bzfs", line 5264, in <module>
    main()
  File "/root/git/bzfs/bzfs/./bzfs", line 1524, in main
    run_main(argument_parser().parse_args(), sys.argv)
  File "/root/git/bzfs/bzfs/./bzfs", line 1531, in run_main
    Job().run_main(args, sys_argv, log)
  File "/root/git/bzfs/bzfs/./bzfs", line 1608, in run_main
    raise e
  File "/root/git/bzfs/bzfs/./bzfs", line 1605, in run_main
    self.run_tasks()
  File "/root/git/bzfs/bzfs/./bzfs", line 1648, in run_tasks
    self.print_replication_stats(start_time_nanos)
  File "/root/git/bzfs/bzfs/./bzfs", line 1685, in print_replication_stats
    total_sent_bytes, tails = count_num_bytes_transferred_by_zfs_send(p.log_params.pv_log_file, maxlen=0)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/git/bzfs/bzfs/./bzfs", line 4419, in count_num_bytes_transferred_by_zfs_send
    total_bytes += pv_size_to_bytes(col)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/root/git/bzfs/bzfs/./bzfs", line 4400, in pv_size_to_bytes
    raise ValueError("Invalid pv_size: " + size)
ValueError: Invalid pv_size: 46,2GiB 0:05:05 [ 154MiB/s] [ 154MiB/s] [===================>] 100%             ETA 17:42:51
```

Is `pv` being filtered through `bzfs`? In that case, maybe the problem is the `,` used instead of `.` in my locale?

(I've attached the pv log below)

**To Reproduce**

`./bzfs --recursive archive/vms vault-disk3/vms`, at least on my machine

**Expected behavior**

I expected progress output, and no backtrace.. :)

**Screenshots or log files**

When trying to replicate the problem, I ran the command again. It seems that it actually finished fine the first time, except for progress output. This is the second run:

```
$ ./bzfs --recursive archive/vms vault-disk3/vms
2024-12-23 18:08:39 [I] Log file is: /root/bzfs-logs/2024-12-23/zrun_2024-12-23_18:08:39-smzt6lu9.log
2024-12-23 18:08:39 [I] CLI arguments:                ./bzfs --recursive archive/vms vault-disk3/vms [euid: 0]
2024-12-23 18:08:40 [I] Starting replication task:    archive/vms -r --> vault-disk3/vms ...
2024-12-23 18:08:40 [I] 1/2 Already up-to-date:       vault-disk3/vms
2024-12-23 18:08:40 [I] 2/2 Already up-to-date:       vault-disk3/vms/iversenit
2024-12-23 18:08:40 [I] Replicated 0 snapshots in 142 ms (0 seconds). zfs sent 0 B (0 bytes) [0 B/s = 0 bytes/s] per pv.
2024-12-23 18:08:40 [I] Log file was: /root/bzfs-logs/2024-12-23/zrun_2024-12-23_18:08:39-smzt6lu9.log
2024-12-23 18:08:40 [I] Success. Goodbye!
```

I managed to dig out the log files. That's a *super* useful feature, but I have to say, I'm really not a big fan of a cli tool creating arbitrary directories in my home dir. I think that goes against the `predictable operations` mentioned in the (by the way, *fantastic*) design aspects.

Might I suggest either asking before creating the directory, or using an appropriate XDG dir, like `~/.local/bzfs/...` ?

**Versions (please complete the following information):**
 - bzfs --version: `bzfs-1.8.0-dev, by Wolfgang Hoschek`
 - zfs --version:
```
zfs-2.2.6-1~bpo12+3
zfs-kmod-2.2.6-1~bpo12+3
```

 - python3 --version: `Python 3.11.2`
 - uname -a: `Linux hostname 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux`

**Attached file**
[bzfs-pv-log-2024-12-23.txt](https://github.com/user-attachments/files/18231743/bzfs-pv-log-2024-12-23.txt)

**Comment by whoschek** [comment]
Yeah, indeed. Thanks for pinpointing the glitch! 
Should be fixed in master now. Let me know if that fixes the issue for you too.

**Comment by whoschek** [comment]
> Might I suggest either asking before creating the directory, or using an appropriate XDG dir, like ~/.local/bzfs/... ?

You can change the log output dir with the --log-dir option. Not sure how widely adopted XGD is across Linux, FreeBSD, Solaris (and at some point in the future OSX). Plus, I'd prefer to use environment variables as little as possible.

**Comment by chrivers** [comment]
Just wanted to report back that this fixes it - thanks for the quick turnaround!
